// Cognito Configuration - Generated by setup script
const cognitoConfig = {
    UserPoolId: 'eu-west-1_HkEC6xpgV',
    ClientId: 'cn83s5vfslmjbibteoq4kfc2b',
    Region: 'eu-west-1',
    Domain: 'photoshare-ognjmwfm.auth.eu-west-1.amazoncognito.com'
};

// Copy these values to your app configuration
console.log('AWS Cognito Configuration:');
console.log('UserPoolId:', cognitoConfig.UserPoolId);
console.log('ClientId:', cognitoConfig.ClientId);
console.log('Region:', cognitoConfig.Region);
console.log('Domain:', cognitoConfig.Domain);


